# Generated by Django 3.2.13 on 2022-06-06 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0053_auto_20220606_1707'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('member_category', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('subgroup', models.CharField(max_length=100, null=True)),
                ('member', models.CharField(max_length=100, null=True)),
                ('outstanding_bill', models.IntegerField(blank=True, null=True)),
                ('payers_first_name', models.CharField(max_length=100, null=True)),
                ('payers_last_name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=500, null=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=100, null=True)),
                ('renewal_period', models.CharField(max_length=100, null=True)),
                ('renewal_bill', models.IntegerField(blank=True, null=True)),
                ('expiration_bill', models.IntegerField(blank=True, null=True)),
                ('total_amount_due', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(max_length=100, null=True)),
                ('arrears', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('invoice_no', models.CharField(blank=True, default='FMS2022661', max_length=500, null=True)),
                ('fee_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feedescription')),
                ('fee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feetype')),
            ],
        ),
        migrations.DeleteModel(
            name='makePayments',
        ),
    ]
