# Generated by Django 4.0.4 on 2022-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_feeitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeitems',
            name='fee_type',
            field=models.CharField(max_length=100),
        ),
    ]
