# Generated by Django 4.0.4 on 2022-05-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0005_alter_feeitems_fee_type_alter_feeitems_id_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeitems',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
