# Generated by Django 4.0.4 on 2022-05-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0007_feesitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fee_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.feesitems'),
        ),
        migrations.DeleteModel(
            name='FeeItems',
        ),
    ]
