# Generated by Django 4.0.4 on 2022-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0008_alter_invoice_fee_items_delete_feeitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=100)),
                ('fee_items', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
