# Generated by Django 4.0.4 on 2022-05-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0009_feeitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fee_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.feeitems'),
        ),
        migrations.DeleteModel(
            name='FeesItems',
        ),
    ]
