# Generated by Django 4.0.4 on 2022-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0011_feesitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
