# Generated by Django 4.0.4 on 2022-05-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0013_alter_feetype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedescription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='FeesItems',
        ),
    ]
