# Generated by Django 4.0.4 on 2022-05-19 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0014_alter_currency_id_alter_feedescription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeitems',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.feetype'),
        ),
    ]
