# Generated by Django 4.0.4 on 2022-05-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0015_alter_feeitems_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeitems',
            name='fee_type',
            field=models.CharField(max_length=100),
        ),
    ]
