# Generated by Django 4.0.4 on 2022-05-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0016_alter_feeitems_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='fee_description',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fee_items',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='fee_type',
        ),
        migrations.DeleteModel(
            name='FeeItems',
        ),
        migrations.DeleteModel(
            name='FeeType',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
