# Generated by Django 4.0.4 on 2022-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0017_remove_invoice_fee_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_type', models.CharField(max_length=100)),
                ('fee_items', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fee_type', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
