# Generated by Django 4.0.4 on 2022-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0019_alter_feeitems_fee_type_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetInvoiceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signers_name', models.CharField(max_length=500)),
                ('signature', models.ImageField(blank=True, default='', null=True, upload_to='signature-uploads/')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='logo-uploads/')),
                ('contact', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
            ],
        ),
    ]
