# Generated by Django 4.0.4 on 2022-05-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0020_setinvoicedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.CharField(default='Home', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AssignPaymentDuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('member_category', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('subgroup', models.CharField(max_length=100)),
                ('total_invoice', models.IntegerField()),
                ('install_payment', models.IntegerField()),
                ('set_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('account_status', models.CharField(max_length=100)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.feetype')),
            ],
        ),
    ]
