# Generated by Django 4.0.4 on 2022-05-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0022_selectedvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedvalue',
            name='selected_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
