# Generated by Django 4.0.4 on 2022-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0024_remove_invoice_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignpaymentduration',
            old_name='install_payment',
            new_name='install_amount',
        ),
        migrations.AddField(
            model_name='assignpaymentduration',
            name='install_days',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='assignpaymentduration',
            name='member',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='set_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='total_invoice',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items_amount',
            field=models.CharField(max_length=100),
        ),
    ]
