# Generated by Django 4.0.4 on 2022-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0025_rename_install_payment_assignpaymentduration_install_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedValue',
        ),
        migrations.AddField(
            model_name='assignpaymentduration',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
