# Generated by Django 4.0.4 on 2022-05-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0026_delete_selectedvalue_assignpaymentduration_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignpaymentduration',
            old_name='install_days',
            new_name='install_period',
        ),
    ]
