# Generated by Django 4.0.4 on 2022-05-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0027_rename_install_days_assignpaymentduration_install_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
