# Generated by Django 4.0.4 on 2022-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0028_assignperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpaymentduration',
            name='install_range',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='install_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='set_date',
            field=models.BooleanField(blank=True),
        ),
    ]
