# Generated by Django 4.0.4 on 2022-05-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0029_assignpaymentduration_install_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='total_invoice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
