# Generated by Django 4.0.4 on 2022-05-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0030_alter_assignpaymentduration_total_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='member',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='member_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='subgroup',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
