# Generated by Django 4.0.4 on 2022-06-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0031_alter_assignpaymentduration_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('member_category', models.CharField(max_length=100, null=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('subgroup', models.CharField(max_length=100, null=True)),
                ('member', models.CharField(max_length=100, null=True)),
                ('outstanding_bill', models.IntegerField(blank=True, default=0)),
                ('payers_name', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('email_address', models.EmailField(max_length=500)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=100, null=True)),
                ('renewal_period', models.CharField(max_length=100)),
                ('renewal_bill', models.IntegerField(blank=True, default=0)),
                ('expiration_bill', models.IntegerField(blank=True, default=0)),
                ('total_amount_due', models.IntegerField(blank=True, default=0)),
                ('payment_status', models.CharField(max_length=100)),
                ('arrears', models.BooleanField()),
                ('fee_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.feedescription')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superuser.feetype')),
            ],
        ),
    ]
