# Generated by Django 4.0.4 on 2022-06-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0032_makepayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetInvoiceDetails',
            new_name='InvoiceDetails',
        ),
    ]
