# Generated by Django 4.0.4 on 2022-06-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0034_remove_invoice_fee_items_invoice_fee_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='set_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
