# Generated by Django 4.0.4 on 2022-06-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0035_alter_assignpaymentduration_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='arrears',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
