# Generated by Django 4.0.4 on 2022-06-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0037_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='total_invoice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
