# Generated by Django 4.0.4 on 2022-06-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0038_alter_assignpaymentduration_total_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='install_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='install_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
