# Generated by Django 4.0.4 on 2022-06-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0039_alter_assignpaymentduration_install_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makepayment',
            old_name='payers_name',
            new_name='payers_first_name',
        ),
        migrations.AddField(
            model_name='makepayment',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='makepayment',
            name='payers_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
