# Generated by Django 4.0.4 on 2022-06-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0040_rename_payers_name_makepayment_payers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepayment',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='arrears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='email_address',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='expiration_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='outstanding_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='payment_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='renewal_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='total_amount_due',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
