# Generated by Django 4.0.4 on 2022-06-04 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0042_alter_makepayment_renewal_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpaymentduration',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='set_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
