# Generated by Django 4.0.4 on 2022-06-04 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0043_assignpaymentduration_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='set_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 4), null=True),
        ),
    ]
