# Generated by Django 4.0.4 on 2022-06-04 01:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0044_alter_assignpaymentduration_set_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='set_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 4, 1, 19, 18, 410450, tzinfo=utc), null=True),
        ),
    ]
