# Generated by Django 4.0.4 on 2022-06-04 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0045_alter_assignpaymentduration_set_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='set_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
