# Generated by Django 4.0.4 on 2022-06-04 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0046_alter_assignpaymentduration_set_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignpaymentduration',
            name='set_date',
        ),
    ]
