# Generated by Django 3.2.13 on 2022-06-04 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0048_assignpaymentduration_set_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='makepayment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
