# Generated by Django 3.2.13 on 2022-06-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0052_auto_20220606_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='fee_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feedescription'),
        ),
        migrations.AlterField(
            model_name='assignpaymentduration',
            name='fee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feetype'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feedescription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feetype'),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='fee_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feedescription'),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='fee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.feetype'),
        ),
    ]
